### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by 23f3002457** [NebulaTris/oss101#121]
name: Aman Sachin Kujur
github_user_name: Aman-Sachin-Kujur

**Comment by amansachinkujur** [comment]
Forked repository: https://github.com/Aman-Sachin-Kujur/oss101
![Screenshot (5)](https://github.com/NebulaTris/oss101/assets/71480625/d5296be2-7f16-4e0e-9d1f-871981a9fccb)

**Comment by amansachinkujur** [comment]
Screenshot of the list of all the current branches inside of my forked local clone repository
![Screenshot (7)](https://github.com/NebulaTris/oss101/assets/71480625/42a3b173-0409-45c7-aafd-9eeec38d2135)
