### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by KSoham-dev** [NebulaTris/oss101#38]
### Beginner/Challenges/01.md
name: Soham Kulkarni
github_user_name: KSoham-dev

**Comment by KSoham2100** [comment]
URL of forked repository: https://github.com/KSoham-dev/oss101fork.git
Screenshot of cloned repository: 
![Screenshot 2024-01-02 141610](https://github.com/NebulaTris/oss101/assets/127087106/0b96b049-dbf8-4250-8d2f-17a72c77eee5)

**Comment by KSoham-dev** [comment]
URL of forked repository: https://github.com/KSoham-dev/oss101fork.git
Screenshot of cloned repository: 
![Screenshot 2024-01-02 141610](https://github.com/NebulaTris/oss101/assets/80382761/2e82cab3-77d4-4317-9d22-eb4c7060f88d)

**Comment by KSoham-dev** [comment]
### Beginner/Challenges/02.md
URL of forked repository: https://github.com/KSoham-dev/oss101fork.git
Screenshot of forked cloned repository: 
![Screenshot 2024-01-02 142442](https://github.com/NebulaTris/oss101/assets/80382761/b894a190-1b57-4624-83ac-b5214d6f5b2d)

**Comment by KSoham-dev** [comment]
### Beginner/Challenges/03.md
![image](https://github.com/NebulaTris/oss101/assets/80382761/0692f6ff-5233-4306-ab36-5faf8b5f1892)

**Comment by KSoham-dev** [comment]
### Intermediate/Challenges/03.md
![Screenshot 2024-01-05 115656](https://github.com/NebulaTris/oss101/assets/80382761/08fb6f5a-95ad-4794-8c11-1a0236fc6d6a)

**Comment by KSoham-dev** [comment]
### Intermediate/Challenges/04.md
![image](https://github.com/NebulaTris/oss101/assets/80382761/1289ba9f-712f-4bed-94de-49ce5bf33929)
