### ISSUE TITLE
Ch 01 [new issue]

### ISSUE THREAD

**Issue by 23f3003507** [NebulaTris/oss101#4]
name: Aakash Deka
github_user_name: aks6-cpu

**Comment by 23f3003507** [comment]
https://github.com/aks6-cpu/oss101.git
![Screenshot 2024-01-03 005815](https://github.com/NebulaTris/oss101/assets/155108255/a89b1de2-86ab-4fbd-bdad-685c7bbde028)

**Comment by aks6-cpu** [comment]
![Uploading Screenshot 2024-01-03 023411.png…]()

**Comment by 23f3003507** [comment]
![Screenshot 2024-01-03 023411](https://github.com/NebulaTris/oss101/assets/155108255/62af943c-3439-4256-a95c-9e37e8c7c402)
