### ISSUE TITLE
Adding info-Beg-challenge-01

### ISSUE THREAD

**Issue by slvignesh05** [NebulaTris/oss101#67]
name: S.Lakshmi Vignesh
github_user_name: https://github.com/izumigoto

**Comment by slvignesh05** [comment]
url:https://github.com/izumigoto/oss101
![image](https://github.com/NebulaTris/oss101/assets/123097688/400d7600-9d56-43a5-a045-abe3ac595e3f)
![Screenshot 2024-01-02 170715](https://github.com/NebulaTris/oss101/assets/123097688/02de839d-7ebc-4dc4-bd59-2a3419df3d5e)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/e81885eb-cc57-4535-830e-1dc7afd1be61)

**Comment by slvignesh05** [comment]
![Screenshot 2024-01-04 181139](https://github.com/NebulaTris/oss101/assets/123097688/44c3b65d-387c-46f4-9bdd-198c79db4452)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/d0f3b0d5-3234-483e-baa4-c6bcd13403ba)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/78f21020-d207-4fb7-b91a-69e8810834af)

**Comment by izumigoto** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/f71d0489-16c4-460f-bbed-151d997af64d)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/7a4d918a-a8e7-48e7-a206-c0e043641eba)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/4f3390cd-5bcf-45d2-b37e-248e5d089662)

**Comment by slvignesh05** [comment]
int -challenge 6 
![image](https://github.com/NebulaTris/oss101/assets/123097688/a9b21a75-cbf6-444b-b436-30515e9db25f)

**Comment by izumigoto** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/7b563e8e-a108-41d3-a046-e01a71c5295c)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/40284785-efb3-42ac-a6f7-31b369d7be2d)

**Comment by slvignesh05** [comment]
![image](https://github.com/NebulaTris/oss101/assets/123097688/22b5aa8d-812f-4ccb-b9c6-95d954d12e56)
![image](https://github.com/NebulaTris/oss101/assets/123097688/d28bd20c-9506-472d-bccd-6bcfd0f65d31)
