### ISSUE TITLE
Aadhirajan Issue for Opensource challenge

### ISSUE THREAD

**Issue by 23f2003968** [NebulaTris/oss101#90]
name: Aadhirajan S
github_user_name: Aadhirajan

**Comment by 23f2003968** [comment]
Challenge 2:
![Screenshot 2024-01-02 234537](https://github.com/NebulaTris/oss101/assets/103513245/669d3e1c-a555-4faf-bcd1-1524ef6bee10)
![Screenshot 2024-01-02 234557](https://github.com/NebulaTris/oss101/assets/103513245/5f51e0fa-b6d6-4c31-85ac-4167d3efbf08)
URL : https://github.com/Aadhirajan/oss101

**Comment by 23f2003968** [comment]
challenge 3:
![Screenshot 2024-01-02 235441](https://github.com/NebulaTris/oss101/assets/103513245/3cb9c29d-dc28-424b-8c80-8b7813e76539)
![Screenshot 2024-01-02 235511](https://github.com/NebulaTris/oss101/assets/103513245/d633bbdd-116b-4012-afff-03b7d5971d9a)

**Comment by 23f2003968** [comment]
Intermediate Challenge 3
![Screenshot 2024-01-05 152611](https://github.com/NebulaTris/oss101/assets/103513245/a69b7465-4a17-4a49-b5a0-dfbab2e9b4d7)

**Comment by 23f2003968** [comment]
Intermediate Challenge 04
![Screenshot 2024-01-05 155110](https://github.com/NebulaTris/oss101/assets/103513245/1f70c943-9586-447e-9aa2-30f8b41b4333)

**Comment by Aadhirajan** [comment]
Intermediate Challenge 05 (merge conflict)
![Uploading Screenshot 2024-01-06 222256.png…]()

**Comment by 23f2003968** [comment]
Intermediate Challenge 05 (merge conflict)
![Screenshot 2024-01-06 222256](https://github.com/NebulaTris/oss101/assets/103513245/8f330b06-334a-45f5-8dba-e1b73b267b5b)
